// Builds the web app into serve/web: index.html, app.js and app.css with fixed names, next to the static design
// system files (tokens.css, components.css, sprite.svg, fonts) that the server already serves as they are.
import {defineConfig} from "vite";
import {svelte} from "@sveltejs/vite-plugin-svelte";
import {readFileSync} from "node:fs";

// `bun run dev` proxies the API to a running Strata server (default: this PC's)
const SERVER = process.env.STRATA_URL || "http://127.0.0.1:8081";
const API = ["/health", "/metrics", "/api", "/settings", "/v1", "/web", "/fonts"];

export default defineConfig({
  plugins: [
    svelte(),
    {
      // the page is served at "/" and its files at "/web/...": relative, so it also works behind a path prefix
      name: "strata-web-paths",
      apply: "build",
      transformIndexHtml: {order: "post", handler: (html) => html.replaceAll('"./app.', '"web/app.')},
    },
    {
      // the expert ranking (data/expert-profile.bin) for the Memory tab, as web/expert-profile.js: the page loads it
      // only when that tab opens, and the server serves .js from serve/web (no server change, no restart)
      name: "strata-expert-profile",
      apply: "build",
      generateBundle() {
        const bin = readFileSync(new URL("../../data/expert-profile.bin", import.meta.url));
        const h = new Uint32Array(bin.buffer.slice(bin.byteOffset + 4, bin.byteOffset + 24));
        if (bin.toString("latin1", 0, 4) !== "STRP") throw new Error("data/expert-profile.bin: not an expert profile");
        const ranked = bin.subarray(24, 24 + h[4] * 4).toString("base64");
        this.emitFile({type: "asset", fileName: "expert-profile.js", source:
          "// generated by serve/web-src/vite.config.js from data/expert-profile.bin: the (layer, expert) pairs, best first\n" +
          `export default ${JSON.stringify({layers: h[1], experts: h[2], ranked})};\n`});
      },
    },
  ],
  base: "./",
  build: {
    outDir: "../web",
    emptyOutDir: false,          // serve/web also holds the design system files and the API monitor page
    assetsDir: "",
    modulePreload: false,
    target: "es2022",
    rollupOptions: {
      output: {
        entryFileNames: "app.js",
        assetFileNames: (a) => (a.names?.[0] || a.name || "").endsWith(".css") ? "app.css" : "[name][extname]",
      },
    },
  },
  server: {proxy: Object.fromEntries(API.map((p) => [p, {target: SERVER, changeOrigin: true}]))},
});
